language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -r requirements.txt
script:
  - flake8 lfsr
  - black -c lfsr
  - isort -c lfsr
  - mypy lfsr
  - pylint lfsr
  - py.test