[tool.black]
line-length = 79
target-version = ['py38']

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
pretty = true
show_column_numbers = true
warn_unused_configs = true

[tool.isort]
profile = "black"
line_length = 79
force_sort_within_sections = true
order_by_type = true

[tool.pytest.ini_options]
python_files = "tests.py test_*.py"
addopts = "--verbose -r s"
